# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('repo_name', models.TextField()),
                ('owner_name', models.CharField(max_length=150)),
                ('review', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
